import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { withdrawalsApi, membersApi, type Withdrawal } from '../api/services';
import { useAuth } from '../contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle, Table, Thead, Tbody, Tr, Th, Td, Button, Input } from '../components/ui/core';
type Shares = Record<string, string>;
export default function Withdrawals() {
  const { isOwner } = useAuth(); const queryClient = useQueryClient(); const { data: withdrawals } = useQuery({ queryKey: ['withdrawals'], queryFn: withdrawalsApi.getAll }); const { data: members } = useQuery({ queryKey: ['members'], queryFn: membersApi.getAll });
  const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [amount, setAmount] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [shares, setShares] = useState<Shares>({}); const [editing, setEditing] = useState<Withdrawal | null>(null);
  const active = members?.data?.filter(m => m.active !== false) || []; const refresh = () => { queryClient.invalidateQueries({ queryKey: ['withdrawals'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); }; const clear = () => { setDescription(''); setCategory(''); setAmount(''); setSelected([]); setShares({}); setEditing(null); };
  const create = useMutation({ mutationFn: withdrawalsApi.create, onSuccess: () => { refresh(); clear(); } }); const update = useMutation({ mutationFn: ({ id, data }: any) => withdrawalsApi.update(id, data), onSuccess: () => { refresh(); clear(); } }); const remove = useMutation({ mutationFn: withdrawalsApi.delete, onSuccess: refresh });
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); const total = Number(amount); if (!total || !selected.length) return; const entered = selected.reduce((sum, id) => sum + (Number(shares[id]) || 0), 0); const blank = selected.filter(id => !shares[id]); if (entered > total || (!blank.length && Math.abs(entered - total) > .01)) return alert('Beneficiary shares must equal the total amount.'); const equal = blank.length ? Number(((total - entered) / blank.length).toFixed(2)) : 0; let remainder = Number((total - entered - equal * blank.length).toFixed(2)); const beneficiaries = selected.map(id => { const share = shares[id] ? Number(shares[id]) : equal + remainder; remainder = 0; return { member_id: id, share }; }); const data = { description, category, amount: total, beneficiaries }; editing ? update.mutate({ id: editing.id, data }) : create.mutate(data); };
  const edit = (w: Withdrawal) => { setEditing(w); setDescription(w.description); setCategory(w.category); setAmount(String(w.amount)); setSelected(w.beneficiaries.map(b => b.member_id)); setShares(Object.fromEntries(w.beneficiaries.map(b => [b.member_id, String(b.share)]))); };
  return <div className="space-y-6"><div><h1 className="page-title">Expenses</h1><p className="page-subtitle">Record shared costs and split them fairly.</p></div>
    {isOwner && <Card><CardHeader><CardTitle>{editing ? 'Edit expense' : 'Record expense'}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><div><label className="form-label">Description</label><Input value={description} onChange={e => setDescription(e.target.value)} required /></div><div><label className="form-label">Category</label><select className="select-control" value={category} onChange={e => setCategory(e.target.value)} required><option value="">Select category</option>{['Food','Accommodation','Transport','Activities','Other'].map(value => <option key={value}>{value}</option>)}</select></div><div><label className="form-label">Total amount</label><Input type="number" min=".01" step=".01" value={amount} onChange={e => setAmount(e.target.value)} required /></div></div><div><div className="flex items-center justify-between"><label className="form-label mb-0">Beneficiaries</label><label className="flex gap-2 text-sm font-semibold text-indigo-600"><input type="checkbox" checked={active.length > 0 && selected.length === active.length} onChange={() => setSelected(selected.length === active.length ? [] : active.map(m => m.id))} />All active members</label></div><p className="mt-1 text-xs text-slate-500">Leave a share blank to split the remainder equally.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{active.map(member => { const on = selected.includes(member.id); return <div key={member.id} className="flex items-center gap-2 rounded-xl border border-white/80 bg-white/40 p-3"><input type="checkbox" checked={on} onChange={() => toggle(member.id)} /><span className="min-w-0 flex-1 truncate text-sm font-medium">{member.display_name || member.name}</span><Input type="number" min="0" step=".01" disabled={!on} value={shares[member.id] || ''} onChange={e => setShares(current => ({ ...current, [member.id]: e.target.value }))} className="h-9 w-24" placeholder="Share" /></div>; })}</div></div><div className="flex gap-2"><Button type="submit">{editing ? 'Save changes' : 'Record expense'}</Button>{editing && <Button type="button" variant="outline" onClick={clear}>Cancel</Button>}</div></form></CardContent></Card>}
    <Card><CardContent className="pt-6"><Table><Thead><Tr><Th>Date</Th><Th>Description</Th><Th>Category</Th><Th>Split among</Th><Th>Amount</Th>{isOwner && <Th>Action</Th>}</Tr></Thead><Tbody>{withdrawals?.data?.map(w => <Tr key={w.id}><Td>{new Date(w.created_at).toLocaleDateString()}</Td><Td>{w.description}</Td><Td>{w.category}</Td><Td>{w.beneficiaries.map(b => b.member_display_name || b.member_name).join(', ')}</Td><Td className="font-medium text-red-600">${w.amount.toFixed(2)}</Td>{isOwner && <Td><div className="flex gap-2"><Button variant="outline" onClick={() => edit(w)}>Edit</Button><Button variant="destructive" onClick={() => remove.mutate(w.id)}>Delete</Button></div></Td>}</Tr>)}</Tbody></Table></CardContent></Card>
  </div>;
}
